# Generated by Django 6.0 on 2025-12-09 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100, verbose_name='Nombre')),
                ('lastname', models.CharField(default='', max_length=150, verbose_name='Apellidos')),
                ('age', models.PositiveSmallIntegerField(verbose_name='Edad')),
            ],
        ),
    ]
