# Generated by Django 6.0 on 2025-12-16 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HolaMundo', '0002_remove_author_lastname_author_last_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True, verbose_name='Título del libro')),
                ('cod', models.CharField(max_length=15, unique=True, verbose_name='Codigo')),
                ('author', models.ManyToManyField(to='HolaMundo.author')),
            ],
        ),
    ]
