# Generated by Django 6.0 on 2025-12-16 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HolaMundo', '0003_book'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'verbose_name': 'Libro', 'verbose_name_plural': 'Libros'},
        ),
    ]
