# Generated by Django 6.0 on 2025-12-16 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HolaMundo', '0004_alter_book_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={},
        ),
    ]
